### ISSUE TITLE
Pressing home or power twice causes apps to become slow with choppy sound

### ISSUE THREAD

**Issue by rsn8887** [devkitPro/SDL#4]
- Start a SDL based homebrew game as application. Ideally one with sound because it makes it easier to notice the problem.
- Press home to go to the menu
- Press home again to return from the menu to the app.
- Observe slow fps and/or choppy/distorted sound

The same happens when pressing the power button to sleep, and pressing the power button again to wake up. Using the power button, the problem happens with applets launched via album, too.

Some apps don’t suspend when pressing the home button. They keep running and playing sounds even after pressing home (why? It is not how commercial games behave). For those apps, the problem only appears when the power button is pressed twice.

**Comment by Cpasjuste** [comment]
Hi @rsn8887 , i think i fixed it by moving to audren for audio, if you want to test it: http://files.mydedibox.fr/files/Dev/nx/libSDL2.a  (https://github.com/devkitPro/SDL/tree/switch-sdl2_audren). I didn't notice any side effect, but i only tested it with sdl2 wav test and pPlay.
