### ISSUE TITLE
Wii U Render: unsafe to delete a recent render target

### ISSUE THREAD

**Issue by ds-sloth** [devkitPro/SDL#76]
### What's the issue you encountered?

While testing our Wii U port of TheXTech engine (https://github.com/TheXTech/TheXTech), my collaborator @Wohlstand found that the engine crashed when `SDL_SetWindowSize` is called to resize the window during initialization. We debugged this further and found it was related to similar crashes when the game's render texture is recreated.

For some reason (I couldn't find the root cause), it seems to be entirely unsafe to delete a texture that was used as a render target in the current frame. Perhaps the result is inadequate GPU synchronization, but I don't know.

This affects cases where the user writes code like `SDL_RenderSetTarget(renderer, NULL); SDL_RenderDeleteTexture(old_target);`, but it also affects seemingly unrelated routines like `SDL_WindowResize(window, ...);`, which recreate the render target internally. The result is a system hang or an emulator crash.

Our workaround was to disable calls to `SDL_WindowResize` (which weren't meaningful) on Wii U, and to delete the second-most recent render target (rather than the most recent one) on Wii U. Both of these represent target-specific code which is generally undesirable in our low-maintenance SDL2 ports of the engine.

### How can the issue be reproduced?

The easiest way to reproduce this crash is to attempt to resize the SDL window during any code using the renderer. Finding the principles underlying a fix for that crash would likely make fixing the render target deletion crash very easy.

### Environment?

I'm using Fedora, but this also affects our CI builds which pull from your Docker image. I really don't think that the environment is related.

### Additional context?

N/A

**Comment by GaryOderNichts** [comment]
I assume by `SDL_WindowResize` you mean `SDL_SetWindowSize`?

**Comment by ds-sloth** [comment]
Yes, my apologies. I just found this repo today, and wrote these notes from my memory of the issue, which I debugged a few days ago.

**Comment by GaryOderNichts** [comment]
I'm unable to reproduce this, but I noticed a small oversight in the GPU synchronization code. Can you check if this issue is still present on the  `wiiu-sdl2-2.28-renderer-improvements`  branch?

**Comment by ds-sloth** [comment]
I'm afraid that on Cemu, this issue *is* still present. Frankly, the main reason I don't have a minimal test for you is that I don't have a preferred test app for SDL render. If you can recommend one to me, then I'll try to make you a minimal test case.

**Comment by GaryOderNichts** [comment]
I just built the latest TheXTech code and removed all the `__WIIU__` specific code in render_sdl.cpp and can't reproduce this on Cemu or Hardware. Is there something I'm missing?

**Comment by ds-sloth** [comment]
Thanks a lot for doing that! There possibly is -- this bug comes up when the render target is resized. Did you go to Options -> Video -> Screen Size and change the resolution?

**Comment by GaryOderNichts** [comment]
Okay, I'm able to reproduce this on Cemu but not on hardware.

**Comment by Wohlstand** [comment]
On hardware this issue gets happen not immediately, you should try to change the resolution multiple time until it get full dead stuck.

**Comment by ds-sloth** [comment]
@Wohlstand, is that true even with Gary's latest changes?

**Comment by Wohlstand** [comment]
I didn't tested that yet, I should make a try on my end now. I explained the buggy behaviour that was done on our end before everything here.

**Comment by GaryOderNichts** [comment]
I just pushed a commit which fixes the issue on both Cemu and hardware. My previous attempt at fixing it didn't work on Cemu due to the way Cemu handles GPU synchronization.

**Comment by Wohlstand** [comment]
Okay, I'll try a bit later, for now I feel sleepy.

**Comment by Wohlstand** [comment]
Oh, I also should try to disable the texture deletion workaround code to see how it work... Thanks for the reminder, glad it's quickly to test that now.

**Comment by Wohlstand** [comment]
I tested the thing (on hardware), I locally removed the workaround for the old target texture preservation, and tested the thing:

https://github.com/user-attachments/assets/1351b7d2-9e35-41b4-826f-bbf8d5a46900

No longer crashes!
